export const CrimeData=[
    {"types":"Burglary","count": 12082},
    {"types": "DUI","count": 12018},
    {"types": "Narcotics","count": 11344},
    {"types": "Assault","count": 9563},
    {"types": "Assault and Battery","count": 8397},
    {"types": "Petty Theft","count": 6656},
    {"types": "Other","count": 6149},
    {"types": "Robbery","count": 5603},
    {"types": "Weapons","count": 4204},
    {"types": "Theft","count": 3290},
    {"types": "Motor Vehicle Theft","count": 2513},
    {"types": "Vandalism","count": 2065},
    {"types": "Local SF Ordinance","count": 1812},
    {"types": "Marijauana","count": 881},
    {"types": "Disorderly Conduct","count": 836},
    {"types": "Other Theft","count": 770},
    {"types": "Other Sex Law Violations","count": 722},
    {"types": "Selected Traffic","count": 708},
    {"types": "Arson","count": 692},
    {"types": "Hit-and-Run","count": 638},
    {"types": "Trespassing","count": 563},
    {"types": "Willful Homicide","count": 403},
    {"types": "Forcible Rape","count": 386},
    {"types": "Willful Homicide (Att.)","count": 337},
    {"types": "Kidnapping","count": 324},
    {"types": "Forgery, Checks, Access Cards","count": 288},
    {"types": "Indecent Exposure","count": 231},
    {"types": "Disturbing Peace","count": 171},
    {"types": "Lewd Conduct","count": 125},
    {"types": "Manslaughter - Vehicular","count": 107},
    {"types": "Prostitution","count": 106},
    {"types": "Malicious Mischief","count": 92},
    {"types": "Escape","count": 43},
    {"types": "Liquor Laws","count": 42},
    {"types": "Manslaughter - Non Vehicular","count": 40},
    {"types": "Lewd or Lascivious","count": 35},
    {"types": "Unlawful Sexual Intercourse","count": 20},
    {"types": "Annoy/Molest Children","count": 18},
    {"types": "Faiulre to Appear/Non-Traffic","count": 16},
    {"types": "Contributing Delinquency of Minor","count": 8},
    {"types": "Gambling","count": 6},
    {"types": "Obscene Matter","count": 3},
    {"types": "Bookmaking","count": 1},
    {"types": "Enhancements","count": 1}
]

